name: "aggressive_growth_screen"
description: "Growth-focused screen for high-growth companies with strong fundamentals"

universe:
  region: "US"
  min_market_cap: 500   # $500M minimum (smaller for growth)
  sectors:
    - "Technology"
    - "Consumer Discretionary" 
    - "Healthcare"
    - "Communication Services"

quality:
  min_roic: 0.10        # 10% minimum (lower for growth)
  min_roe: 0.12         # 12% minimum
  min_current_ratio: 1.0 # More flexible
  max_debt_equity: 1.0   # Can handle more debt for growth

value:
  max_pe: 40            # Higher P/E acceptable for growth
  max_pb: 8.0           # Higher P/B acceptable
  max_ev_ebitda: 25     # Higher multiples OK

growth:
  min_revenue_growth: 0.15  # Minimum 15% revenue growth
  min_earnings_growth: 0.20 # Minimum 20% earnings growth

risk:
  max_beta: 2.0         # Can handle more volatility
  cyclical_adjustment: false

valuation:
  models: ["dcf"]       # Focus on DCF for growth
  scenarios: ["base", "bull"]
  dcf_years: 10
  terminal_growth_rate: 0.035  # Higher terminal growth

max_results: 20
sort_by: "growth_score"
generate_reports: true
save_data: true