#!/bin/bash
echo "🚀 Starting Investment Analysis MCP Server"
echo "========================================="
echo ""
echo "This MCP server provides AI assistants with access to:"
echo "• 15+ valuation models (DCF, neural networks, ratios, etc.)"
echo "• Multi-timeframe neural network predictions"
echo "• Comprehensive stock analysis and comparisons"
echo "• Real-time financial data with intelligent caching"
echo ""
echo "Available tools:"
echo "  - analyze_stock: Complete analysis with multiple models"
echo "  - neural_predict: AI-powered predictions with timeframes"
echo "  - get_model_info: Learn about available models"
echo "  - quick_compare: Fast 3-model comparison"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

uv run python mcp_server_v2.py