# Backtesting configuration for buying ONLY the biggest stock
# This tests the extreme case of maximum concentration
name: market_cap_top1_backtest

# Backtest period
start_date: '2020-01-01'
end_date: '2024-01-01'

# Initial capital
initial_capital: 100000

# Rebalancing frequency: monthly, quarterly, annually
rebalance_frequency: annually  # Less frequent since we're only holding one stock

# Strategy type
strategy_type: market_cap

# Investment universe - S&P 500 stocks
universe:
  - AAPL
  - MSFT
  - AMZN
  - NVDA
  - GOOGL
  - META
  - TSLA
  - BRK-B
  - JPM
  - JNJ
  - V
  - PG
  - UNH
  - MA
  - HD
  - DIS
  - BAC
  - ABBV
  - PFE
  - COST
  - WMT
  - CVX
  - XOM
  - KO
  - PEP
  # ETFs for comparison
  - SPY  # S&P 500 ETF

# Portfolio constraints
max_positions: 1  # Only allow one position
min_position_size: 0.90  # 90% minimum (almost all-in)
max_position_size: 0.95  # 95% maximum (keep some cash)

# Transaction costs
transaction_cost: 0.001  # 0.1% per trade
slippage: 0.001  # 0.1% slippage

# Benchmark for comparison
benchmark: SPY

# Market Cap Strategy specific configuration
strategy:
  # Buy only the single biggest stock
  max_positions: 1
  
  # Doesn't matter for single stock, but let's use market_cap
  weighting: market_cap
  
  # No minimum market cap filter needed
  min_market_cap: 0
  
  # Higher threshold since we're only holding one stock
  rebalance_threshold: 0.10  # 10% drift triggers rebalancing